name: Purge Cache

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  purge:
    runs-on: ubuntu-latest

    steps:
      - name: Purge README.md Image Cache
        run: curl -s https://github.com/neogeek/advent-of-code-2022/blob/main/README.md | grep -Eo '<img src="https://camo.githubusercontent.com/[^"]+' | grep -Eo 'https[^"]+' | xargs -I {} curl -w "\n" -s -X PURGE {}
