name: Tests

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install Deno
        run: curl -fsSL https://deno.land/x/install/install.sh | sh

      - name: Run tests
        timeout-minutes: 5
        run: |
          export PATH="~/.deno/bin:$PATH"
          deno test --allow-read
